export interface AmrepArtist {
  id: number;
  name: string;
  description?: string;
}

export const amrepArtists: AmrepArtist[] = [
  { id: 1, name: "Bailter Space" },
  { id: 42, name: "Billy Childish" },
  { id: 43, name: "The Blind Shake" },
  { id: 2, name: "Boredoms" },
  { id: 3, name: "Boss Hog" },
  { id: 4, name: "Brainiac" },
  { id: 44, name: "Bush Pig" },
  { id: 5, name: "Calvin Krime" },
  { id: 45, name: "Casus Belli" },
  { id: 46, name: "Cherubs" },
  { id: 6, name: "Chokebore" },
  { id: 7, name: "Cosmic Psychos" },
  { id: 8, name: "Cows" },
  { id: 47, name: "The Crows" },
  { id: 48, name: "Crystal Fairy" },
  { id: 49, name: "Dale Crover" },
  { id: 50, name: "Die Nerven" },
  { id: 10, name: "feedtime" },
  { id: 51, name: "Freedom Fighters" },
  { id: 12, name: "Gaunt" },
  { id: 53, name: "Gear Jammer" },
  { id: 54, name: "Gnomes of Zurich" },
  { id: 13, name: "God Bullies" },
  { id: 14, name: "godheadSilo" },
  { id: 55, name: "Grant Hart" },
  { id: 56, name: "Guzzard" },
  { id: 15, name: "Halo of Flies / H•O•F" },
  { id: 16, name: "Hammerhead" },
  { id: 57, name: "The Hand" },
  { id: 58, name: "Haze XXL" },
  { id: 59, name: "Hedonists" },
  { id: 17, name: "Helios Creed" },
  { id: 18, name: "Helmet", description: "Alternative metal band with the AmRep debut 'Strap It On'." },
  { id: 60, name: "Hepa-Titus" },
  { id: 19, name: "The Heroine Sheiks" },
  { id: 20, name: "Janitor Joe" },
  { id: 21, name: "Killdozer" },
  { id: 61, name: "King Buzzo" },
  { id: 22, name: "King Snake Roost" },
  { id: 62, name: "Lifter Puller" },
  { id: 63, name: "Lollipop" },
  { id: 64, name: "Lonely Moans" },
  { id: 65, name: "Love 666" },
  { id: 23, name: "lowercase" },
  { id: 24, name: "Lubricated Goat" },
  { id: 66, name: "Lydia Lunch" },
  { id: 67, name: "Mama Tick" },
  { id: 25, name: "Melvins", description: "Noise rock band long associated with AmRep's roster." },
  { id: 68, name: "Mog Stunt Team" },
  { id: 69, name: "mr.phylzzz" },
  { id: 26, name: "Nashville Pussy" },
  { id: 70, name: "Operation: Break Even" },
  { id: 71, name: "Party Diktator" },
  { id: 72, name: "Pogo the Clown" },
  { id: 73, name: "The Powers That Be" },
  { id: 74, name: "S.W.A.T." },
  { id: 75, name: "Seawhores" },
  { id: 27, name: "Servotron" },
  { id: 76, name: "Silver Salute" },
  { id: 28, name: "Steel Pole Bath Tub" },
  { id: 29, name: "Strapping Fieldhands" },
  { id: 31, name: "Supernova" },
  { id: 30, name: "Surgery" },
  { id: 32, name: "Tad" },
  { id: 33, name: "Tar" },
  { id: 77, name: "Teenage Jesus and the Jerks" },
  { id: 34, name: "Thee Headcoats" },
  { id: 35, name: "Thee Mighty Caesars" },
  { id: 36, name: "The Thrown Ups" },
  { id: 39, name: "Today Is the Day" },
  { id: 37, name: "The U-Men" },
  { id: 40, name: "Unsane" },
  { id: 38, name: "The Urinals" },
  { id: 41, name: "Vertigo" },
  { id: 78, name: "White Drugs" },
  { id: 79, name: "Whopping Big Naughty" },
  { id: 80, name: "X" },
];

export function getAmrepArtistById(id: number): AmrepArtist | undefined {
  return amrepArtists.find((artist) => artist.id === id);
}
