export interface AmrepRelease {
  id: number;
  title: string;
  artist: string;
  year: number;
  format: string;
  highlight?: string;
}

export const amrepReleases: AmrepRelease[] = [
  {
    id: 1,
    title: "Strap It On",
    artist: "Helmet",
    year: 1990,
    format: "LP",
    highlight: "AmRep’s breakout release, later cited as vital to the label’s growth.",
  },
  {
    id: 2,
    title: "Dope-Guns-'N-Fucking in the Streets Volumes 4-7",
    artist: "Various Artists",
    year: 1990,
    format: "Compilation",
  },
  {
    id: 3,
    title: "Peacetika",
    artist: "Cows",
    year: 1991,
    format: "CS",
  },
  {
    id: 4,
    title: "Music for Insect Minds",
    artist: "Halo of Flies",
    year: 1991,
    format: "CD",
  },
  {
    id: 5,
    title: "Lactating Purple",
    artist: "Helios Creed",
    year: 1991,
    format: "CD, CS, LP",
  },
  {
    id: 6,
    title: "Jackson",
    artist: "Tar",
    year: 1991,
    format: "CD, CS, LP",
  },
  {
    id: 7,
    title: "Blokes You Can Trust",
    artist: "Cosmic Psychos",
    year: 1991,
    format: "CD, CS, LP",
  },
  {
    id: 8,
    title: "War on Everybody",
    artist: "God Bullies",
    year: 1991,
    format: "CD, CS",
  },
  {
    id: 9,
    title: "Cunning Stunts",
    artist: "Cows",
    year: 1991,
    format: "CD, CS, LP",
  },
  {
    id: 10,
    title: "Motionless",
    artist: "Chokebore",
    year: 1991,
    format: "CD, CS, LP",
  },
  {
    id: 11,
    title: "Ventriloquist",
    artist: "Vertigo",
    year: 1992,
    format: "CD, CS, LP",
  },
  {
    id: 12,
    title: "Kiss to the Brain",
    artist: "Helios Creed",
    year: 1992,
    format: "CD, CS, LP",
  },
  {
    id: 13,
    title: "Ethereal Killer",
    artist: "Hammerhead",
    year: 1992,
    format: "CD, CS",
    highlight: "Hammerhead’s AmRep debut, raw and abrasive Midwestern noise rock.",
  },
  {
    id: 14,
    title: "Girl +",
    artist: "Boss Hog",
    year: 1993,
    format: "CD, LP",
  },
  {
    id: 15,
    title: "Trim, 9th Ward High Roller",
    artist: "Surgery",
    year: 1993,
    format: "CD, CS, LP",
  },
  {
    id: 16,
    title: "Palomino Pizza",
    artist: "Cosmic Psychos",
    year: 1993,
    format: "CD, CS, LP",
  },
  {
    id: 17,
    title: "Nail Hole",
    artist: "Vertigo",
    year: 1993,
    format: "CD, CS",
  },
  {
    id: 18,
    title: "Supernova",
    artist: "Today Is the Day",
    year: 1993,
    format: "CD, CS, LP",
  },
  {
    id: 19,
    title: "Evil Twin",
    artist: "Hammerhead",
    year: 1993,
    format: "CD, CS",
  },
  {
    id: 20,
    title: "Clusterfuck '94",
    artist: "Various Artists",
    year: 1994,
    format: "Compilation",
  },
  {
    id: 21,
    title: "Days of Nothing",
    artist: "Chokebore",
    year: 1994,
    format: "LP",
  },
  {
    id: 22,
    title: "Into the Vortex",
    artist: "Hammerhead",
    year: 1994,
    format: "CD, CS, LP",
    highlight: "Hammerhead at full power—one of AmRep’s fiercest full-lengths.",
  },
  {
    id: 23,
    title: "Orphan's Tragedy",
    artist: "Cows",
    year: 1994,
    format: "CD, CS",
  },
  {
    id: 24,
    title: "Prick",
    artist: "Melvins",
    year: 1994,
    format: "CD, CS, LP",
  },
  {
    id: 25,
    title: "Willpower",
    artist: "Today Is the Day",
    year: 1994,
    format: "CD, LP",
  },
  {
    id: 26,
    title: "Anything Near Water",
    artist: "Chokebore",
    year: 1995,
    format: "CD, CS, LP",
  },
  {
    id: 27,
    title: "AmRep Motors 1995 Models",
    artist: "Various Artists",
    year: 1995,
    format: "Compilation",
  },
  {
    id: 28,
    title: "Born Annoying",
    artist: "Helmet",
    year: 1995,
    format: "CD, CS, LP",
  },
  {
    id: 29,
    title: "Self Totalled",
    artist: "Cosmic Psychos",
    year: 1995,
    format: "CD, LP",
  },
  {
    id: 30,
    title: "Scattered, Smothered & Covered",
    artist: "Unsane",
    year: 1995,
    format: "CD, CS, LP",
  },
  {
    id: 31,
    title: "Duh, The Big City",
    artist: "Hammerhead",
    year: 1996,
    format: "CD",
  },
  {
    id: 32,
    title: "It Could Ruin Your Day",
    artist: "Chokebore",
    year: 1996,
    format: "LP",
  },
  {
    id: 33,
    title: "A Taste for Bitters",
    artist: "Chokebore",
    year: 1996,
    format: "CD",
  },
  {
    id: 34,
    title: "AmRep Equipped 96/97",
    artist: "Various Artists",
    year: 1997,
    format: "Compilation",
  },
  {
    id: 35,
    title: "Dress for the Future",
    artist: "Calvin Krime",
    year: 1997,
    format: "CD, LP",
  },
  {
    id: 36,
    title: "You're Feeling So Attractive",
    artist: "Calvin Krime",
    year: 1998,
    format: "CD, LP",
  },
  {
    id: 37,
    title: "Sorry in Pig Minor",
    artist: "Cows",
    year: 1998,
    format: "CD, LP",
  },
  {
    id: 38,
    title: "Let Them Eat Pussy",
    artist: "Nashville Pussy",
    year: 1998,
    format: "CD, CS, LP",
  },
  {
    id: 39,
    title: "Rox",
    artist: "Supernova",
    year: 1998,
    format: "CD",
  },
  {
    id: 40,
    title: "Journey to the End of the Knife",
    artist: "The Heroine Sheiks",
    year: 2008,
    format: "CD",
  },
  {
    id: 41,
    title: "Gay Witch Abortion Sessions",
    artist: "Halo of Flies",
    year: 2009,
    format: "CD, LP",
  },
  {
    id: 42,
    title: "Gold Magic",
    artist: "White Drugs",
    year: 2010,
    format: "CD, LP",
  },
  {
    id: 43,
    title: "Anarcho Retardist Terror Exhibit",
    artist: "Hammerhead",
    year: 2011,
    format: "LP",
    highlight: "Hammerhead’s long-awaited return on AmRep.",
  },
  {
    id: 44,
    title: "Big Metal Birds",
    artist: "Janitor Joe",
    year: 1993,
    format: "CD, CS",
  },
  {
    id: 45,
    title: "Sexy Pee Story",
    artist: "Cows",
    year: 1993,
    format: "CD, CS",
  },
  {
    id: 46,
    title: "Get a Witness",
    artist: "Guzzard",
    year: 1993,
    format: "CD, CS",
  },
  {
    id: 47,
    title: "Down on the Farm & Cosmic Psychos",
    artist: "Cosmic Psychos",
    year: 1992,
    format: "CD",
  },
  {
    id: 48,
    title: 'Noise Archives Volume 1: X - "Aspirations"',
    artist: "X",
    year: 1992,
    format: "CD",
  },
  {
    id: 49,
    title: "Lucky",
    artist: "Janitor Joe",
    year: 1994,
    format: "CD, CS",
  },
  {
    id: 50,
    title: "Deep Inside a Cop's Mind",
    artist: "S.W.A.T.",
    year: 1994,
    format: "CD, CS, LP",
  },
  {
    id: 51,
    title: "The Crows",
    artist: "The Crows",
    year: 1994,
    format: "CD",
  },
  {
    id: 52,
    title: "Planet X",
    artist: "Helios Creed",
    year: 1994,
    format: "CD, CS",
  },
  {
    id: 53,
    title: "Screwed: Original Motion Picture Soundtrack",
    artist: "Various Artists",
    year: 1996,
    format: "CD",
  },
  {
    id: 54,
    title: "Operation: Break Even",
    artist: "Various Artists",
    year: 1996,
    format: "CD",
  },
  {
    id: 55,
    title: "Negative Capability...Check It Out!",
    artist: "Urinals",
    year: 1996,
    format: "CD",
  },
  {
    id: 56,
    title: "Today Is the Day",
    artist: "Today Is the Day",
    year: 1996,
    format: "CD, CS, LP",
  },
  {
    id: 57,
    title: "Old Gold 1989–1991",
    artist: "Cows",
    year: 1996,
    format: "CD, CS",
  },
  {
    id: 58,
    title: "Whorn",
    artist: "Cows",
    year: 1996,
    format: "CD, CS, LP",
  },
  {
    id: 59,
    title: "Yeah, Me Too",
    artist: "Gaunt",
    year: 1995,
    format: "CD, LP",
  },
  {
    id: 60,
    title: "American Revolution",
    artist: "Love 666",
    year: 1995,
    format: "CD, LP",
  },
  {
    id: 61,
    title: "Please Kill Yourself So I Can Rock",
    artist: "Love 666",
    year: 1996,
    format: "CD, LP",
  },
  {
    id: 62,
    title: "All Destructive Urges... Seem So Perfect",
    artist: "lowercase",
    year: 1996,
    format: "CD, CS",
  },
  {
    id: 63,
    title: "Billy",
    artist: "feedtime",
    year: 1996,
    format: "CD, CS, LP",
  },
  {
    id: 64,
    title: "No Room for Humans",
    artist: "Servotron",
    year: 1997,
    format: "CD, LP",
  },
  {
    id: 65,
    title: "Kill the Lights",
    artist: "lowercase",
    year: 1997,
    format: "CD, LP",
  },
  {
    id: 66,
    title: "Oh What a Lovely Pie",
    artist: "Cosmic Psychos",
    year: 1997,
    format: "CD",
  },
  {
    id: 67,
    title: "Ages 3 and Up",
    artist: "Supernova",
    year: 1995,
    format: "LP",
  },
  {
    id: 68,
    title: "Singles 1-12",
    artist: "Melvins",
    year: 1997,
    format: "CD",
  },
  {
    id: 69,
    title: "Honky",
    artist: "Melvins",
    year: 1997,
    format: "CD, LP",
  },
  {
    id: 70,
    title: "Alive at the Fucker Club",
    artist: "Melvins",
    year: 1998,
    format: "CD, LP",
  },
  {
    id: 71,
    title: "Melvins vs. Minneapolis",
    artist: "Melvins",
    year: 2008,
    format: "CD",
  },
  {
    id: 72,
    title: "Hurray for Me Fuk You",
    artist: "Melvins",
    year: 2010,
    format: "LP",
  },
  {
    id: 73,
    title: "The Bride Screamed Murder",
    artist: "Melvins",
    year: 2011,
    format: "LP",
  },
  {
    id: 74,
    title: "Endless Residency",
    artist: "Melvins",
    year: 2011,
    format: "CD",
  },
  {
    id: 75,
    title: "Drinkin', Lechin' & Lyin'",
    artist: "Boss Hog",
    year: 2016,
    format: "LP",
  },
];

export function getAmrepReleaseById(id: number): AmrepRelease | undefined {
  return amrepReleases.find((release) => release.id === id);
}
