export const localAlbumImages: Record<number, string> = {
  1: "/images/e6/releases/release-1.jpg",
  2: "/images/e6/releases/release-2.jpg",
  3: "/images/e6/releases/release-3.jpg",
  4: "/images/e6/releases/release-4.jpg",
  5: "/images/e6/releases/release-5.jpg",
  6: "/images/e6/releases/release-6.jpg",
  7: "/images/e6/releases/release-7.jpg",
  8: "/images/e6/releases/release-8.jpg",
  9: "/images/e6/releases/release-9.jpg",
  10: "/images/e6/releases/release-10.jpg",
  11: "/images/e6/releases/release-11.jpg",
  12: "/images/e6/releases/release-12.jpg",
  13: "/images/e6/releases/release-13.jpg",
  14: "/images/e6/releases/release-14.jpg",
  15: "/images/e6/releases/release-15.jpg",
  16: "/images/e6/releases/release-16.jpg",
  17: "/images/e6/releases/release-17.jpg",
  18: "/images/e6/releases/release-18.jpg",
  19: "/images/e6/releases/release-19.jpg",
  20: "/images/e6/releases/release-20.jpg",
  21: "/images/e6/releases/release-21.jpg",
  22: "/images/e6/releases/release-22.jpg",
  23: "/images/e6/releases/release-23.jpg",
  24: "/images/e6/releases/release-24.jpg",
  25: "/images/e6/releases/release-25.jpg",
  26: "/images/e6/releases/release-26.jpg",
  27: "/images/e6/releases/release-27.jpg",
  28: "/images/e6/releases/release-28.jpg",
  29: "/images/e6/releases/release-29.jpg",
  30: "/images/e6/releases/release-30.jpg",
  31: "/images/e6/releases/release-31.jpg",
  33: "/images/e6/releases/release-33.jpg",
  34: "/images/e6/releases/release-34.jpg",
  35: "/images/e6/releases/release-35.jpg",
  36: "/images/e6/releases/release-36.jpg",
  37: "/images/e6/releases/release-37.jpg",
  38: "/images/e6/releases/release-38.jpg",
  39: "/images/e6/releases/release-39.jpg",
  40: "/images/e6/releases/release-40.jpg",
  41: "/images/e6/releases/release-41.jpg",
  42: "/images/e6/releases/release-42.jpg",
  43: "/images/e6/releases/release-43.jpg",
  44: "/images/e6/releases/release-44.jpg",
  45: "/images/e6/releases/release-45.jpg",
  46: "/images/e6/releases/release-46.jpg",
  47: "/images/e6/releases/release-47.jpg",
  48: "/images/e6/releases/release-48.jpg",
  49: "/images/e6/releases/release-49.jpg",
  50: "/images/e6/releases/release-50.jpg",
};

export function getLocalAlbumImage(catalogNumber: number): string | null {
  return localAlbumImages[catalogNumber] || null;
}
