export interface GbvTriviaQuestion {
  id: number;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  category: "history" | "albums" | "songs" | "members" | "facts";
}

export const gbvTriviaQuestions: GbvTriviaQuestion[] = [
  // ===== HISTORY (30 questions) =====
  {
    id: 1,
    question: "In what year was Guided By Voices formed?",
    options: ["1981", "1983", "1985", "1987"],
    correctAnswer: 1,
    explanation: "Guided By Voices was formed in 1983 in Dayton, Ohio.",
    category: "history",
  },
  {
    id: 2,
    question: "Which Ohio city is Guided By Voices from?",
    options: ["Columbus", "Cleveland", "Dayton", "Cincinnati"],
    correctAnswer: 2,
    explanation: "Guided By Voices formed in Dayton, Ohio.",
    category: "history",
  },
  {
    id: 3,
    question: "What year did GBV originally break up?",
    options: ["2002", "2003", "2004", "2005"],
    correctAnswer: 2,
    explanation: "Guided By Voices broke up in 2004 after the release of Half Smiles of the Decomposed.",
    category: "history",
  },
  {
    id: 4,
    question: "What year did GBV reunite with their classic lineup?",
    options: ["2008", "2009", "2010", "2011"],
    correctAnswer: 2,
    explanation: "GBV reunited in 2010 with the classic lineup of Pollard, Sprout, Mitchell, and Fennell.",
    category: "history",
  },
  {
    id: 5,
    question: "What was Robert Pollard's day job before music became his full-time career?",
    options: ["Accountant", "Schoolteacher", "Factory worker", "Postal worker"],
    correctAnswer: 1,
    explanation: "Robert Pollard was a schoolteacher in Dayton, Ohio before dedicating himself to music full-time.",
    category: "history",
  },
  {
    id: 6,
    question: "Which major indie label signed GBV in the mid-1990s?",
    options: ["Sub Pop", "Merge", "Matador", "Drag City"],
    correctAnswer: 2,
    explanation: "Matador Records was GBV's main label throughout the 1990s.",
    category: "history",
  },
  {
    id: 7,
    question: "What was GBV's final album before their 2004 breakup?",
    options: ["Universal Truths and Cycles", "Earthquake Glue", "Half Smiles of the Decomposed", "Isolation Drills"],
    correctAnswer: 2,
    explanation: "Half Smiles of the Decomposed (2004) was the last GBV album before their breakup.",
    category: "history",
  },
  {
    id: 8,
    question: "What was GBV's first album after reuniting?",
    options: ["Class Clown Spots a UFO", "The Bears for Lunch", "Let's Go Eat the Factory", "English Little League"],
    correctAnswer: 2,
    explanation: "Let's Go Eat the Factory (2012) was the first post-reunion album.",
    category: "history",
  },
  {
    id: 9,
    question: "Which label released GBV's Do the Collapse in 1999?",
    options: ["Matador", "TVT Records", "Scat Records", "Merge"],
    correctAnswer: 1,
    explanation: "TVT Records released Do the Collapse in 1999.",
    category: "history",
  },
  {
    id: 10,
    question: "How many studio albums did GBV release in 2012 alone?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 2,
    explanation: "GBV released three albums in 2012: Let's Go Eat the Factory, Class Clown Spots a UFO, and The Bears for Lunch.",
    category: "history",
  },
  {
    id: 11,
    question: "What was GBV's debut album?",
    options: ["Propeller", "Devil Between My Toes", "Self-Inflicted Aerial Nostalgia", "Same Place the Fly Got Smashed"],
    correctAnswer: 1,
    explanation: "Devil Between My Toes (1987) was GBV's debut album.",
    category: "history",
  },
  {
    id: 12,
    question: "How many studio albums did GBV release in 2019?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 2,
    explanation: "GBV released three albums in 2019: Zeppelin Over China, Warp and Woof, and Sweating the Plague.",
    category: "history",
  },
  {
    id: 13,
    question: "How many studio albums did GBV release in 2022?",
    options: ["2", "3", "4", "5"],
    correctAnswer: 2,
    explanation: "GBV released four albums in 2022: Crystal Nuns Cathedral, Tremblers and Goggles by Rank, La La Land, and Welshpool Frillies.",
    category: "history",
  },
  {
    id: 14,
    question: "Which festival famously featured a GBV reunion performance in 2010?",
    options: ["Bonnaroo", "Coachella", "Matador at 21", "Lollapalooza"],
    correctAnswer: 2,
    explanation: "GBV reunited for the Matador at 21 anniversary festival in 2010.",
    category: "history",
  },
  {
    id: 15,
    question: "What was GBV's first album released on Matador Records?",
    options: ["Propeller", "Vampire on Titus", "Bee Thousand", "Alien Lanes"],
    correctAnswer: 2,
    explanation: "Bee Thousand (1994) was GBV's first release on Matador Records.",
    category: "history",
  },
  {
    id: 16,
    question: "How many studio albums did GBV release in 2020?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 2,
    explanation: "GBV released three albums in 2020: Surrender Your Poppy Field, Mirrored Aztec, and Styles We Paid For.",
    category: "history",
  },
  {
    id: 17,
    question: "What was GBV's first self-released album?",
    options: ["Devil Between My Toes", "Sandbox", "Propeller", "Forever Since Breakfast"],
    correctAnswer: 0,
    explanation: "Devil Between My Toes (1987) was GBV's first self-released album.",
    category: "history",
  },
  {
    id: 18,
    question: "In what decade did GBV gain widespread indie rock recognition?",
    options: ["1980s", "1990s", "2000s", "2010s"],
    correctAnswer: 1,
    explanation: "GBV gained widespread recognition in the 1990s, particularly with Bee Thousand and Alien Lanes.",
    category: "history",
  },
  {
    id: 19,
    question: "Which album marked GBV's shift toward more polished production in 1996?",
    options: ["Mag Earwhig!", "Do the Collapse", "Under the Bushes Under the Stars", "Tonics & Twisted Chasers"],
    correctAnswer: 2,
    explanation: "Under the Bushes Under the Stars (1996) featured higher production values than previous albums.",
    category: "history",
  },
  {
    id: 20,
    question: "How many albums did GBV release in 2021?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 1,
    explanation: "GBV released two albums in 2021: Earth Man Blues and It's Not Them. It Couldn't Be Them. It Is Them!",
    category: "history",
  },
  {
    id: 21,
    question: "What is the name of GBV's 2024 album?",
    options: ["Welshpool Frillies", "Janitor Revealed", "Strut of Kings", "La La Land"],
    correctAnswer: 2,
    explanation: "Strut of Kings was released in 2024.",
    category: "history",
  },
  {
    id: 22,
    question: "What is the name of GBV's 2023 album?",
    options: ["Strut of Kings", "Janitor Revealed", "La La Land", "Welshpool Frillies"],
    correctAnswer: 1,
    explanation: "Janitor Revealed was released in 2023.",
    category: "history",
  },
  {
    id: 23,
    question: "Which year saw the release of Propeller?",
    options: ["1990", "1991", "1992", "1993"],
    correctAnswer: 2,
    explanation: "Propeller was released in 1992.",
    category: "history",
  },
  {
    id: 24,
    question: "Approximately how many studio albums has GBV released in total through 2024?",
    options: ["15-20", "20-25", "25-30", "30+"],
    correctAnswer: 3,
    explanation: "GBV has released over 30 studio albums, making them one of the most prolific rock bands.",
    category: "history",
  },
  {
    id: 25,
    question: "What was the first GBV album released after the classic lineup departed post-reunion?",
    options: ["Cool Planet", "Motivational Jumpsuit", "Please Be Honest", "August by Cake"],
    correctAnswer: 2,
    explanation: "Please Be Honest (2016) was credited to GBV but was essentially a Pollard solo effort after the classic lineup departed again.",
    category: "history",
  },
  {
    id: 26,
    question: "Which small label released early GBV albums like Propeller and Vampire on Titus?",
    options: ["Matador", "Scat Records", "TVT Records", "Merge"],
    correctAnswer: 1,
    explanation: "Scat Records released several early GBV albums before the band moved to Matador.",
    category: "history",
  },
  {
    id: 27,
    question: "What year was Vampire on Titus released?",
    options: ["1991", "1992", "1993", "1994"],
    correctAnswer: 2,
    explanation: "Vampire on Titus was released in 1993.",
    category: "history",
  },
  {
    id: 28,
    question: "Which album was the last GBV record on Matador before the original breakup?",
    options: ["Do the Collapse", "Isolation Drills", "Under the Bushes Under the Stars", "Universal Truths and Cycles"],
    correctAnswer: 2,
    explanation: "Under the Bushes Under the Stars (1996) was GBV's last album on Matador before moving to TVT.",
    category: "history",
  },
  {
    id: 29,
    question: "In what year was Isolation Drills released?",
    options: ["1999", "2000", "2001", "2002"],
    correctAnswer: 2,
    explanation: "Isolation Drills was released in 2001.",
    category: "history",
  },
  {
    id: 30,
    question: "Which year saw GBV release both Motivational Jumpsuit and Cool Planet?",
    options: ["2013", "2014", "2015", "2016"],
    correctAnswer: 1,
    explanation: "Both Motivational Jumpsuit and Cool Planet were released in 2014.",
    category: "history",
  },
  // ===== ALBUMS (30 questions) =====
  {
    id: 31,
    question: "Which GBV album is often cited as their lo-fi breakthrough?",
    options: ["Alien Lanes", "Bee Thousand", "Mag Earwhig!", "Under the Bushes Under the Stars"],
    correctAnswer: 1,
    explanation: "Bee Thousand (1994) is widely viewed as their breakthrough album.",
    category: "albums",
  },
  {
    id: 32,
    question: "What year was Bee Thousand released?",
    options: ["1992", "1993", "1994", "1995"],
    correctAnswer: 2,
    explanation: "Bee Thousand was released in 1994 on Matador Records.",
    category: "albums",
  },
  {
    id: 33,
    question: "What is the approximate track count on Alien Lanes?",
    options: ["12", "18", "28", "36"],
    correctAnswer: 2,
    explanation: "Alien Lanes contains 28 tracks, exemplifying GBV's prolific style.",
    category: "albums",
  },
  {
    id: 34,
    question: "Which label released Alien Lanes?",
    options: ["Matador", "Sub Pop", "Merge", "Drag City"],
    correctAnswer: 0,
    explanation: "Alien Lanes was released on Matador Records in 1995.",
    category: "albums",
  },
  {
    id: 35,
    question: "What year was Alien Lanes released?",
    options: ["1993", "1994", "1995", "1996"],
    correctAnswer: 2,
    explanation: "Alien Lanes was released in 1995.",
    category: "albums",
  },
  {
    id: 36,
    question: "Who produced Do the Collapse?",
    options: ["Steve Albini", "Ric Ocasek", "Bob Mould", "Robert Pollard"],
    correctAnswer: 1,
    explanation: "Ric Ocasek of The Cars produced Do the Collapse (1999).",
    category: "albums",
  },
  {
    id: 37,
    question: "What year was Do the Collapse released?",
    options: ["1997", "1998", "1999", "2000"],
    correctAnswer: 2,
    explanation: "Do the Collapse was released in 1999 on TVT Records.",
    category: "albums",
  },
  {
    id: 38,
    question: "What year was Under the Bushes Under the Stars released?",
    options: ["1994", "1995", "1996", "1997"],
    correctAnswer: 2,
    explanation: "Under the Bushes Under the Stars was released in 1996.",
    category: "albums",
  },
  {
    id: 39,
    question: "What year was Mag Earwhig! released?",
    options: ["1995", "1996", "1997", "1998"],
    correctAnswer: 2,
    explanation: "Mag Earwhig! was released in 1997.",
    category: "albums",
  },
  {
    id: 40,
    question: "What is the title of GBV's 1987 debut album?",
    options: ["Propeller", "Devil Between My Toes", "Sandbox", "Self-Inflicted Aerial Nostalgia"],
    correctAnswer: 1,
    explanation: "Devil Between My Toes was GBV's 1987 debut album.",
    category: "albums",
  },
  {
    id: 41,
    question: "What year was Universal Truths and Cycles released?",
    options: ["2000", "2001", "2002", "2003"],
    correctAnswer: 2,
    explanation: "Universal Truths and Cycles was released in 2002.",
    category: "albums",
  },
  {
    id: 42,
    question: "Which GBV album was produced by Ric Ocasek?",
    options: ["Isolation Drills", "Mag Earwhig!", "Do the Collapse", "Under the Bushes Under the Stars"],
    correctAnswer: 2,
    explanation: "Do the Collapse (1999) was produced by Ric Ocasek of The Cars.",
    category: "albums",
  },
  {
    id: 43,
    question: "What is the name of GBV's first post-reunion album from 2012?",
    options: ["The Bears for Lunch", "Let's Go Eat the Factory", "Class Clown Spots a UFO", "English Little League"],
    correctAnswer: 1,
    explanation: "Let's Go Eat the Factory was the first post-reunion album, released in January 2012.",
    category: "albums",
  },
  {
    id: 44,
    question: "Which GBV album has 'Decomposed' in the title?",
    options: ["Universal Truths and Cycles", "Isolation Drills", "Half Smiles of the Decomposed", "Earthquake Glue"],
    correctAnswer: 2,
    explanation: "Half Smiles of the Decomposed (2004) was the final album before the breakup.",
    category: "albums",
  },
  {
    id: 45,
    question: "What is the full title of GBV's 2021 album abbreviated as 'INTICTIII'?",
    options: [
      "It's Not Them. It Couldn't Be Them. It Is Them!",
      "In No Time. It Can't Take Itself. It Is Time!",
      "It's Never True. It Can't Be True. It Is True!",
      "In New Towns. It Couldn't Be Towns. It Is Towns!",
    ],
    correctAnswer: 0,
    explanation: "The full title is It's Not Them. It Couldn't Be Them. It Is Them! (2021).",
    category: "albums",
  },
  {
    id: 46,
    question: "Which GBV album has a title referencing outer space and China?",
    options: ["Space Gun", "Zeppelin Over China", "Cool Planet", "Alien Lanes"],
    correctAnswer: 1,
    explanation: "Zeppelin Over China was released in 2019.",
    category: "albums",
  },
  {
    id: 47,
    question: "What is the title of GBV's 2018 album?",
    options: ["Warp and Woof", "Space Gun", "August by Cake", "How Do You Spell Heaven"],
    correctAnswer: 1,
    explanation: "Space Gun was released in 2018.",
    category: "albums",
  },
  {
    id: 48,
    question: "Which two GBV albums were released in 2017?",
    options: [
      "Space Gun and Zeppelin Over China",
      "Please Be Honest and August by Cake",
      "August by Cake and How Do You Spell Heaven",
      "How Do You Spell Heaven and Space Gun",
    ],
    correctAnswer: 2,
    explanation: "August by Cake and How Do You Spell Heaven were both released in 2017.",
    category: "albums",
  },
  {
    id: 49,
    question: "What year was English Little League released?",
    options: ["2012", "2013", "2014", "2015"],
    correctAnswer: 1,
    explanation: "English Little League was released in 2013.",
    category: "albums",
  },
  {
    id: 50,
    question: "Which 2020 GBV album has a floral reference in its title?",
    options: ["Mirrored Aztec", "Styles We Paid For", "Surrender Your Poppy Field", "Earth Man Blues"],
    correctAnswer: 2,
    explanation: "Surrender Your Poppy Field was released in 2020.",
    category: "albums",
  },
  {
    id: 51,
    question: "What is the name of GBV's 2016 album?",
    options: ["Cool Planet", "Motivational Jumpsuit", "Please Be Honest", "August by Cake"],
    correctAnswer: 2,
    explanation: "Please Be Honest was released in 2016.",
    category: "albums",
  },
  {
    id: 52,
    question: "Which GBV album title contains the word 'Nuns'?",
    options: ["La La Land", "Crystal Nuns Cathedral", "Welshpool Frillies", "Tremblers and Goggles by Rank"],
    correctAnswer: 1,
    explanation: "Crystal Nuns Cathedral was released in 2022.",
    category: "albums",
  },
  {
    id: 53,
    question: "What is the title of GBV's album that references a 'Plague'?",
    options: ["Warp and Woof", "Zeppelin Over China", "Sweating the Plague", "Surrender Your Poppy Field"],
    correctAnswer: 2,
    explanation: "Sweating the Plague was released in 2019.",
    category: "albums",
  },
  {
    id: 54,
    question: "Which album title contains the words 'Tremblers and Goggles'?",
    options: ["Crystal Nuns Cathedral", "Tremblers and Goggles by Rank", "Welshpool Frillies", "Janitor Revealed"],
    correctAnswer: 1,
    explanation: "Tremblers and Goggles by Rank was released in 2022.",
    category: "albums",
  },
  {
    id: 55,
    question: "What GBV album features the word 'Jumpsuit' in its title?",
    options: ["Cool Planet", "English Little League", "Motivational Jumpsuit", "Class Clown Spots a UFO"],
    correctAnswer: 2,
    explanation: "Motivational Jumpsuit was released in 2014.",
    category: "albums",
  },
  {
    id: 56,
    question: "Which GBV album from 2021 references 'Blues' in its title?",
    options: ["Sweating the Plague", "Earth Man Blues", "Styles We Paid For", "Mirrored Aztec"],
    correctAnswer: 1,
    explanation: "Earth Man Blues was released in 2021.",
    category: "albums",
  },
  {
    id: 57,
    question: "What is the name of GBV's album that shares its title with a Ryan Gosling movie?",
    options: ["Cool Planet", "La La Land", "Half Smiles of the Decomposed", "Space Gun"],
    correctAnswer: 1,
    explanation: "La La Land was released in 2022.",
    category: "albums",
  },
  {
    id: 58,
    question: "Which GBV album has a Welsh place name in its title?",
    options: ["Crystal Nuns Cathedral", "Janitor Revealed", "Welshpool Frillies", "Tremblers and Goggles by Rank"],
    correctAnswer: 2,
    explanation: "Welshpool Frillies was released in 2022.",
    category: "albums",
  },
  {
    id: 59,
    question: "What is the title of the GBV album released between The Bears for Lunch and English Little League?",
    options: ["Let's Go Eat the Factory", "Class Clown Spots a UFO", "Motivational Jumpsuit", "Cool Planet"],
    correctAnswer: 0,
    explanation: "Let's Go Eat the Factory, Class Clown Spots a UFO, and The Bears for Lunch were all released in 2012, followed by English Little League in 2013.",
    category: "albums",
  },
  {
    id: 60,
    question: "Which GBV album's title contains the word 'Aztec'?",
    options: ["Surrender Your Poppy Field", "Mirrored Aztec", "Styles We Paid For", "Zeppelin Over China"],
    correctAnswer: 1,
    explanation: "Mirrored Aztec was released in 2020.",
    category: "albums",
  },
  // ===== SONGS (30 questions) =====
  {
    id: 61,
    question: "Which GBV album features the song 'I Am a Scientist'?",
    options: ["Propeller", "Bee Thousand", "Alien Lanes", "Under the Bushes Under the Stars"],
    correctAnswer: 1,
    explanation: "'I Am a Scientist' appears on Bee Thousand (1994).",
    category: "songs",
  },
  {
    id: 62,
    question: "Which album contains the song 'Game of Pricks'?",
    options: ["Bee Thousand", "Alien Lanes", "Mag Earwhig!", "Under the Bushes Under the Stars"],
    correctAnswer: 1,
    explanation: "'Game of Pricks' appears on Alien Lanes (1995).",
    category: "songs",
  },
  {
    id: 63,
    question: "On which album does 'Motor Away' appear?",
    options: ["Bee Thousand", "Alien Lanes", "Under the Bushes Under the Stars", "Propeller"],
    correctAnswer: 1,
    explanation: "'Motor Away' appears on Alien Lanes (1995).",
    category: "songs",
  },
  {
    id: 64,
    question: "Which album features the song 'Echos Myron'?",
    options: ["Under the Bushes Under the Stars", "Alien Lanes", "Bee Thousand", "Mag Earwhig!"],
    correctAnswer: 2,
    explanation: "'Echos Myron' appears on Bee Thousand (1994).",
    category: "songs",
  },
  {
    id: 65,
    question: "On which album does 'Tractor Rape Chain' appear?",
    options: ["Alien Lanes", "Bee Thousand", "Propeller", "Vampire on Titus"],
    correctAnswer: 1,
    explanation: "'Tractor Rape Chain' appears on Bee Thousand (1994).",
    category: "songs",
  },
  {
    id: 66,
    question: "Which album features 'My Valuable Hunting Knife'?",
    options: ["Vampire on Titus", "Propeller", "Bee Thousand", "Alien Lanes"],
    correctAnswer: 2,
    explanation: "'My Valuable Hunting Knife' appears on Bee Thousand (1994).",
    category: "songs",
  },
  {
    id: 67,
    question: "On which album does 'Glad Girls' appear?",
    options: ["Do the Collapse", "Isolation Drills", "Universal Truths and Cycles", "Half Smiles of the Decomposed"],
    correctAnswer: 1,
    explanation: "'Glad Girls' appears on Isolation Drills (2001).",
    category: "songs",
  },
  {
    id: 68,
    question: "Which album features the song 'Teenage FBI'?",
    options: ["Mag Earwhig!", "Do the Collapse", "Isolation Drills", "Under the Bushes Under the Stars"],
    correctAnswer: 1,
    explanation: "'Teenage FBI' appears on Do the Collapse (1999).",
    category: "songs",
  },
  {
    id: 69,
    question: "On which album does 'Hot Freaks' appear?",
    options: ["Bee Thousand", "Alien Lanes", "Propeller", "Vampire on Titus"],
    correctAnswer: 0,
    explanation: "'Hot Freaks' appears on Bee Thousand (1994).",
    category: "songs",
  },
  {
    id: 70,
    question: "Which album features 'Gold Star for Robot Boy'?",
    options: ["Alien Lanes", "Bee Thousand", "Under the Bushes Under the Stars", "Mag Earwhig!"],
    correctAnswer: 1,
    explanation: "'Gold Star for Robot Boy' appears on Bee Thousand (1994).",
    category: "songs",
  },
  {
    id: 71,
    question: "On which album does 'A Salty Salute' appear?",
    options: ["Bee Thousand", "Alien Lanes", "Under the Bushes Under the Stars", "Propeller"],
    correctAnswer: 1,
    explanation: "'A Salty Salute' appears on Alien Lanes (1995).",
    category: "songs",
  },
  {
    id: 72,
    question: "Which album contains 'Buzzards and Dreadful Crows'?",
    options: ["Alien Lanes", "Bee Thousand", "Propeller", "Self-Inflicted Aerial Nostalgia"],
    correctAnswer: 2,
    explanation: "'Buzzards and Dreadful Crows' appears on Propeller (1992).",
    category: "songs",
  },
  {
    id: 73,
    question: "On which album does 'Smothered in Hugs' appear?",
    options: ["Alien Lanes", "Bee Thousand", "Propeller", "Vampire on Titus"],
    correctAnswer: 1,
    explanation: "'Smothered in Hugs' appears on Bee Thousand (1994).",
    category: "songs",
  },
  {
    id: 74,
    question: "Which album features 'Cut-Out Witch'?",
    options: ["Under the Bushes Under the Stars", "Alien Lanes", "Bee Thousand", "Propeller"],
    correctAnswer: 1,
    explanation: "'Cut-Out Witch' appears on Alien Lanes (1995).",
    category: "songs",
  },
  {
    id: 75,
    question: "Which song opens the album Bee Thousand?",
    options: ["Echos Myron", "Hardcore UFOs", "Buzzards and Dreadful Crows", "I Am a Scientist"],
    correctAnswer: 1,
    explanation: "'Hardcore UFOs' is the opening track on Bee Thousand.",
    category: "songs",
  },
  {
    id: 76,
    question: "Which GBV song contains the lyric 'I am a scientist, I seek to understand me'?",
    options: ["Echos Myron", "I Am a Scientist", "Motor Away", "Game of Pricks"],
    correctAnswer: 1,
    explanation: "This lyric is from 'I Am a Scientist' on Bee Thousand.",
    category: "songs",
  },
  {
    id: 77,
    question: "Which Bee Thousand song features the lyrics about 'the inalienable right to be lazy'?",
    options: ["Tractor Rape Chain", "Gold Star for Robot Boy", "Echos Myron", "Hot Freaks"],
    correctAnswer: 2,
    explanation: "'Echos Myron' features various surreal lyrical passages and is one of GBV's most beloved songs.",
    category: "songs",
  },
  {
    id: 78,
    question: "On which album does 'Watch Me Jumpstart' appear?",
    options: ["Alien Lanes", "Bee Thousand", "Under the Bushes Under the Stars", "Propeller"],
    correctAnswer: 1,
    explanation: "'Watch Me Jumpstart' appears on Alien Lanes (1995).",
    category: "songs",
  },
  {
    id: 79,
    question: "Which album features the song 'The Goldheart Mountaintop Queen Directory'?",
    options: ["Bee Thousand", "Alien Lanes", "Propeller", "Vampire on Titus"],
    correctAnswer: 0,
    explanation: "'The Goldheart Mountaintop Queen Directory' appears on Bee Thousand (1994).",
    category: "songs",
  },
  {
    id: 80,
    question: "On which album does 'Don't Stop Now' appear?",
    options: ["Under the Bushes Under the Stars", "Alien Lanes", "Bee Thousand", "Mag Earwhig!"],
    correctAnswer: 0,
    explanation: "'Don't Stop Now' appears on Under the Bushes Under the Stars (1996).",
    category: "songs",
  },
  {
    id: 81,
    question: "Which album features 'Bulldog Skin'?",
    options: ["Mag Earwhig!", "Under the Bushes Under the Stars", "Do the Collapse", "Isolation Drills"],
    correctAnswer: 1,
    explanation: "'Bulldog Skin' appears on Under the Bushes Under the Stars (1996).",
    category: "songs",
  },
  {
    id: 82,
    question: "On which album does 'I Am a Tree' appear?",
    options: ["Mag Earwhig!", "Under the Bushes Under the Stars", "Do the Collapse", "Alien Lanes"],
    correctAnswer: 0,
    explanation: "'I Am a Tree' appears on Mag Earwhig! (1997).",
    category: "songs",
  },
  {
    id: 83,
    question: "Which album features the song 'Chasing Heather Crazy'?",
    options: ["Do the Collapse", "Isolation Drills", "Under the Bushes Under the Stars", "Mag Earwhig!"],
    correctAnswer: 2,
    explanation: "'Chasing Heather Crazy' appears on Under the Bushes Under the Stars (1996).",
    category: "songs",
  },
  {
    id: 84,
    question: "On which album does 'The Official Ironmen Rally Song' appear?",
    options: ["Under the Bushes Under the Stars", "Mag Earwhig!", "Alien Lanes", "Do the Collapse"],
    correctAnswer: 0,
    explanation: "'The Official Ironmen Rally Song' appears on Under the Bushes Under the Stars (1996).",
    category: "songs",
  },
  {
    id: 85,
    question: "Which album contains 'Hold on Hope'?",
    options: ["Isolation Drills", "Do the Collapse", "Universal Truths and Cycles", "Half Smiles of the Decomposed"],
    correctAnswer: 1,
    explanation: "'Hold on Hope' appears on Do the Collapse (1999).",
    category: "songs",
  },
  {
    id: 86,
    question: "On which album does 'Skills Like This' appear?",
    options: ["Isolation Drills", "Do the Collapse", "Mag Earwhig!", "Universal Truths and Cycles"],
    correctAnswer: 0,
    explanation: "'Skills Like This' appears on Isolation Drills (2001).",
    category: "songs",
  },
  {
    id: 87,
    question: "Which album features 'My Kind of Soldier'?",
    options: ["Universal Truths and Cycles", "Isolation Drills", "Half Smiles of the Decomposed", "Earthquake Glue"],
    correctAnswer: 0,
    explanation: "'My Kind of Soldier' appears on Universal Truths and Cycles (2002).",
    category: "songs",
  },
  {
    id: 88,
    question: "Which GBV song was notably used in the trailer for the film 'Boyhood'?",
    options: ["Motor Away", "Game of Pricks", "I Am a Scientist", "Teenage FBI"],
    correctAnswer: 0,
    explanation: "'Motor Away' was featured in promotional material for Richard Linklater's Boyhood.",
    category: "songs",
  },
  {
    id: 89,
    question: "On which album does 'Exit Flagger' appear?",
    options: ["Alien Lanes", "Bee Thousand", "Propeller", "Under the Bushes Under the Stars"],
    correctAnswer: 2,
    explanation: "'Exit Flagger' appears on Propeller (1992).",
    category: "songs",
  },
  {
    id: 90,
    question: "Which album features the song 'Over the Neptune / Mesh Gear Fox'?",
    options: ["Propeller", "Bee Thousand", "Alien Lanes", "Vampire on Titus"],
    correctAnswer: 2,
    explanation: "'Over the Neptune / Mesh Gear Fox' appears on Alien Lanes (1995).",
    category: "songs",
  },
  // ===== MEMBERS (30 questions) =====
  {
    id: 91,
    question: "Who is the primary songwriter and vocalist of Guided By Voices?",
    options: ["Tobin Sprout", "Robert Pollard", "Kevin Fennell", "Mitch Mitchell"],
    correctAnswer: 1,
    explanation: "Robert Pollard is the band's primary songwriter and vocalist, and the only constant member.",
    category: "members",
  },
  {
    id: 92,
    question: "Who played guitar and sang in the classic GBV lineup alongside Pollard?",
    options: ["Doug Gillard", "Nate Farley", "Tobin Sprout", "Bobby Bare Jr."],
    correctAnswer: 2,
    explanation: "Tobin Sprout played guitar and contributed vocals and songs to the classic lineup.",
    category: "members",
  },
  {
    id: 93,
    question: "Who was the drummer in the classic GBV lineup?",
    options: ["Jim Macpherson", "Kevin March", "Kevin Fennell", "Don Thrasher"],
    correctAnswer: 2,
    explanation: "Kevin Fennell was the drummer in the classic GBV lineup.",
    category: "members",
  },
  {
    id: 94,
    question: "Which guitarist joined GBV for the Mag Earwhig! era?",
    options: ["Nate Farley", "Doug Gillard", "Bobby Bare Jr.", "Tobin Sprout"],
    correctAnswer: 1,
    explanation: "Doug Gillard joined GBV for the Mag Earwhig! album in 1997.",
    category: "members",
  },
  {
    id: 95,
    question: "Who plays bass in GBV's current (2024) lineup?",
    options: ["Greg Demos", "Tim Tobias", "Mark Shue", "Chris Slusarenko"],
    correctAnswer: 2,
    explanation: "Mark Shue plays bass in the current GBV lineup.",
    category: "members",
  },
  {
    id: 96,
    question: "Who is the drummer in GBV's current (2024) lineup?",
    options: ["Kevin Fennell", "Jim Macpherson", "Kevin March", "Jon McCann"],
    correctAnswer: 2,
    explanation: "Kevin March is the drummer in the current GBV lineup.",
    category: "members",
  },
  {
    id: 97,
    question: "Which country music artist's son plays in GBV's current lineup?",
    options: ["Bobby Bare Jr.", "Hank Williams III", "Shooter Jennings", "Justin Townes Earle"],
    correctAnswer: 0,
    explanation: "Bobby Bare Jr., son of country legend Bobby Bare, is in GBV's current lineup.",
    category: "members",
  },
  {
    id: 98,
    question: "Who played guitar in the classic GBV lineup (not Tobin Sprout)?",
    options: ["Doug Gillard", "Mitch Mitchell", "Nate Farley", "Bobby Bare Jr."],
    correctAnswer: 1,
    explanation: "Mitch Mitchell played guitar in the classic GBV lineup.",
    category: "members",
  },
  {
    id: 99,
    question: "Which GBV member also has a notable solo career as a painter and musician?",
    options: ["Robert Pollard", "Tobin Sprout", "Doug Gillard", "Kevin Fennell"],
    correctAnswer: 1,
    explanation: "Tobin Sprout has a solo career as both a musician and a visual artist/painter.",
    category: "members",
  },
  {
    id: 100,
    question: "Which Robert Pollard side project was a power trio active from 2008-2011?",
    options: ["Circus Devils", "Boston Spaceships", "Ricked Wicky", "Lifeguards"],
    correctAnswer: 1,
    explanation: "Boston Spaceships was a Pollard side project active from 2008 to 2011.",
    category: "members",
  },
  {
    id: 101,
    question: "Which experimental side project features Robert Pollard collaborating with Todd Tobias?",
    options: ["Boston Spaceships", "Circus Devils", "Ricked Wicky", "Airport 5"],
    correctAnswer: 1,
    explanation: "Circus Devils is a collaboration between Robert Pollard and Todd Tobias.",
    category: "members",
  },
  {
    id: 102,
    question: "How many members are in GBV's current (2024) lineup?",
    options: ["3", "4", "5", "6"],
    correctAnswer: 2,
    explanation: "The current lineup has five members: Pollard, Gillard, March, Shue, and Bare Jr.",
    category: "members",
  },
  {
    id: 103,
    question: "Which four members made up the 'classic lineup' that reunited in 2010?",
    options: [
      "Pollard, Gillard, March, Slusarenko",
      "Pollard, Sprout, Mitchell, Fennell",
      "Pollard, Sprout, Gillard, Fennell",
      "Pollard, Mitchell, Farley, March",
    ],
    correctAnswer: 1,
    explanation: "The classic lineup was Pollard, Sprout, Mitchell, and Fennell.",
    category: "members",
  },
  {
    id: 104,
    question: "Which member of GBV's current lineup also plays guitar alongside Pollard?",
    options: ["Mark Shue", "Kevin March", "Doug Gillard", "Bobby Bare Jr."],
    correctAnswer: 2,
    explanation: "Doug Gillard plays lead guitar in the current GBV lineup.",
    category: "members",
  },
  {
    id: 105,
    question: "Besides GBV, what is Robert Pollard also known for?",
    options: [
      "Producing hip-hop albums",
      "A prolific solo career with dozens of albums",
      "Acting in indie films",
      "Writing novels",
    ],
    correctAnswer: 1,
    explanation: "Robert Pollard has released dozens of solo albums in addition to his GBV work.",
    category: "members",
  },
  {
    id: 106,
    question: "Which GBV guitarist was also a member of Cobra Verde?",
    options: ["Tobin Sprout", "Nate Farley", "Doug Gillard", "Bobby Bare Jr."],
    correctAnswer: 2,
    explanation: "Doug Gillard was a member of Cobra Verde before joining GBV.",
    category: "members",
  },
  {
    id: 107,
    question: "What instrument does Bobby Bare Jr. play in the current GBV lineup?",
    options: ["Bass", "Drums", "Guitar", "Keyboards"],
    correctAnswer: 2,
    explanation: "Bobby Bare Jr. plays guitar in the current GBV lineup.",
    category: "members",
  },
  {
    id: 108,
    question: "Who is the only member who has been in every iteration of GBV?",
    options: ["Tobin Sprout", "Mitch Mitchell", "Robert Pollard", "Kevin Fennell"],
    correctAnswer: 2,
    explanation: "Robert Pollard is the only constant member across all GBV lineups.",
    category: "members",
  },
  {
    id: 109,
    question: "Which classic-lineup member played drums?",
    options: ["Mitch Mitchell", "Tobin Sprout", "Kevin Fennell", "Robert Pollard"],
    correctAnswer: 2,
    explanation: "Kevin Fennell was the drummer in the classic lineup.",
    category: "members",
  },
  {
    id: 110,
    question: "What was Tobin Sprout's role in the classic GBV lineup?",
    options: [
      "Drums",
      "Bass",
      "Guitar, vocals, and songwriting",
      "Keyboards",
    ],
    correctAnswer: 2,
    explanation: "Tobin Sprout contributed guitar, vocals, and songwriting to the classic lineup.",
    category: "members",
  },
  {
    id: 111,
    question: "Which side project did Pollard form with Chris Slusarenko?",
    options: ["Circus Devils", "Boston Spaceships", "Airport 5", "Lifeguards"],
    correctAnswer: 2,
    explanation: "Airport 5 was a collaboration between Robert Pollard and Chris Slusarenko.",
    category: "members",
  },
  {
    id: 112,
    question: "What instrument does Mark Shue play in GBV?",
    options: ["Guitar", "Drums", "Bass", "Keyboards"],
    correctAnswer: 2,
    explanation: "Mark Shue plays bass in GBV.",
    category: "members",
  },
  {
    id: 113,
    question: "Which former GBV drummer later played with the Breeders?",
    options: ["Kevin Fennell", "Jim Macpherson", "Kevin March", "Don Thrasher"],
    correctAnswer: 1,
    explanation: "Jim Macpherson played drums in GBV and also with the Breeders.",
    category: "members",
  },
  {
    id: 114,
    question: "Which Tobin Sprout solo album was released in 1996?",
    options: ["Carnival Boy", "Moonflower Plastic", "Let's Welcome the Circus People", "Lost Planets & Animal Beings"],
    correctAnswer: 0,
    explanation: "Tobin Sprout released Carnival Boy in 1996 during the peak of GBV's classic era.",
    category: "members",
  },
  {
    id: 115,
    question: "How many guitarists are in GBV's current (2024) lineup?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 2,
    explanation: "The current lineup has three guitarists: Pollard, Gillard, and Bare Jr. (Pollard also sings).",
    category: "members",
  },
  {
    id: 116,
    question: "Which member joined GBV's current lineup as the newest addition?",
    options: ["Doug Gillard", "Kevin March", "Mark Shue", "Bobby Bare Jr."],
    correctAnswer: 3,
    explanation: "Bobby Bare Jr. is among the newer additions to the current GBV lineup.",
    category: "members",
  },
  {
    id: 117,
    question: "What is the name of a Pollard solo album from 2001?",
    options: ["Fiction Man", "Waved Out", "Not in My Airforce", "Motel of Fools"],
    correctAnswer: 2,
    explanation: "Not in My Airforce is one of Robert Pollard's solo records.",
    category: "members",
  },
  {
    id: 118,
    question: "Which producer worked with Boston Spaceships alongside Pollard?",
    options: ["Ric Ocasek", "Todd Tobias", "Steve Albini", "Rob Schnapf"],
    correctAnswer: 1,
    explanation: "Todd Tobias was the main collaborator in Boston Spaceships with Pollard.",
    category: "members",
  },
  {
    id: 119,
    question: "Mitch Mitchell's primary instrument in GBV was what?",
    options: ["Bass", "Drums", "Guitar", "Keyboards"],
    correctAnswer: 2,
    explanation: "Mitch Mitchell played guitar in the classic GBV lineup.",
    category: "members",
  },
  {
    id: 120,
    question: "What role does Robert Pollard primarily serve in GBV besides singing?",
    options: ["Drummer", "Bassist", "Guitarist and songwriter", "Keyboardist"],
    correctAnswer: 2,
    explanation: "Pollard is the primary songwriter and also plays guitar in GBV.",
    category: "members",
  },
  // ===== FACTS (30 questions) =====
  {
    id: 121,
    question: "GBV is best known for what recording approach on early albums?",
    options: ["High-budget studio polish", "Lo-fi DIY home recordings", "Live-only releases", "Electronic production"],
    correctAnswer: 1,
    explanation: "GBV's hallmark is lo-fi, DIY home recording, often on four-track cassette recorders.",
    category: "facts",
  },
  {
    id: 122,
    question: "What is Robert Pollard famously known for doing during GBV live shows?",
    options: [
      "Playing acoustic sets",
      "High kicks and drinking beer",
      "Crowd surfing",
      "Playing extended guitar solos",
    ],
    correctAnswer: 1,
    explanation: "Pollard is famous for his energetic high kicks and prolific beer drinking during live performances.",
    category: "facts",
  },
  {
    id: 123,
    question: "GBV live shows are known for being what kind of events?",
    options: [
      "Short 30-minute sets",
      "Acoustic unplugged performances",
      "Marathon shows with 50+ songs",
      "Elaborately staged productions",
    ],
    correctAnswer: 2,
    explanation: "GBV is known for marathon live shows that can feature 50 or more songs in a single performance.",
    category: "facts",
  },
  {
    id: 124,
    question: "What beverage is most closely associated with GBV's live performances?",
    options: ["Whiskey", "Wine", "Beer", "Tequila"],
    correctAnswer: 2,
    explanation: "Beer is the beverage most associated with GBV concerts, with Pollard famously drinking throughout performances.",
    category: "facts",
  },
  {
    id: 125,
    question: "What type of recording device was commonly used on early GBV albums?",
    options: ["Digital workstation", "Four-track cassette recorder", "48-track studio console", "Reel-to-reel tape"],
    correctAnswer: 1,
    explanation: "Many early GBV albums were recorded on four-track cassette recorders, contributing to their lo-fi sound.",
    category: "facts",
  },
  {
    id: 126,
    question: "GBV is frequently cited as one of the most prolific bands due to what?",
    options: [
      "Releasing the longest songs in rock",
      "Releasing an enormous number of albums",
      "Playing the most instruments",
      "Having the most members",
    ],
    correctAnswer: 1,
    explanation: "GBV has released over 30 studio albums and countless EPs and compilations, making them extraordinarily prolific.",
    category: "facts",
  },
  {
    id: 127,
    question: "Where were many classic-era GBV albums recorded?",
    options: [
      "Professional studios in New York",
      "Basements and garages in Dayton, Ohio",
      "A studio in Nashville",
      "Abbey Road Studios",
    ],
    correctAnswer: 1,
    explanation: "Many classic GBV albums were recorded in basements and garages in Dayton, Ohio.",
    category: "facts",
  },
  {
    id: 128,
    question: "What profession did Robert Pollard hold while making early GBV records?",
    options: ["Lawyer", "Doctor", "Schoolteacher", "Engineer"],
    correctAnswer: 2,
    explanation: "Robert Pollard was a fourth-grade schoolteacher in Dayton while making GBV's early albums.",
    category: "facts",
  },
  {
    id: 129,
    question: "How many songs did GBV sometimes include on a single album?",
    options: ["8-10", "12-15", "20-28", "40+"],
    correctAnswer: 2,
    explanation: "Albums like Alien Lanes (28 tracks) and Bee Thousand (20 tracks) feature very high track counts.",
    category: "facts",
  },
  {
    id: 130,
    question: "What is distinctive about the length of many GBV songs?",
    options: [
      "They are mostly over 7 minutes",
      "They are frequently very short, often under 2 minutes",
      "They are all exactly 3 minutes",
      "They feature long instrumental sections",
    ],
    correctAnswer: 1,
    explanation: "Many GBV songs are very short, frequently under two minutes, some even under one minute.",
    category: "facts",
  },
  {
    id: 131,
    question: "What is a common description of Robert Pollard's lyrical style?",
    options: [
      "Straightforward narrative storytelling",
      "Abstract, surreal, and fragmented imagery",
      "Political protest lyrics",
      "Confessional autobiography",
    ],
    correctAnswer: 1,
    explanation: "Pollard's lyrics are known for abstract, surreal, and fragmented poetic imagery.",
    category: "facts",
  },
  {
    id: 132,
    question: "Early copies of which GBV album came with unique hand-assembled packaging?",
    options: ["Bee Thousand", "Propeller", "Vampire on Titus", "Devil Between My Toes"],
    correctAnswer: 1,
    explanation: "Early copies of Propeller (1992) came in unique hand-assembled covers, each one different.",
    category: "facts",
  },
  {
    id: 133,
    question: "How many albums did GBV release in the year 2022?",
    options: ["2", "3", "4", "5"],
    correctAnswer: 2,
    explanation: "GBV released four albums in 2022: Crystal Nuns Cathedral, Tremblers and Goggles by Rank, La La Land, and Welshpool Frillies.",
    category: "facts",
  },
  {
    id: 134,
    question: "What aspect of British music is often cited as a major influence on GBV?",
    options: [
      "British punk rock",
      "British Invasion and post-punk",
      "British electronic music",
      "British folk music",
    ],
    correctAnswer: 1,
    explanation: "GBV is heavily influenced by British Invasion bands and post-punk groups like Wire and The Who.",
    category: "facts",
  },
  {
    id: 135,
    question: "What do fans commonly bring to GBV concerts?",
    options: ["Flowers", "Beer for the band", "Signs with song requests", "Vinyl records to sign"],
    correctAnswer: 1,
    explanation: "Fans commonly bring beer to GBV shows, keeping with the band's beer-soaked reputation.",
    category: "facts",
  },
  {
    id: 136,
    question: "What is notable about GBV's song titles?",
    options: [
      "They are always one word",
      "They are often surreal, cryptic, or absurd",
      "They are always named after places",
      "They are always numbered",
    ],
    correctAnswer: 1,
    explanation: "GBV song titles are frequently surreal, cryptic, or absurd, like 'Tractor Rape Chain' and 'Gold Star for Robot Boy'.",
    category: "facts",
  },
  {
    id: 137,
    question: "What do many GBV songs sound like they could be fragments of?",
    options: [
      "Jazz compositions",
      "Classical symphonies",
      "Longer, fully realized pop songs",
      "Electronic tracks",
    ],
    correctAnswer: 2,
    explanation: "Many GBV songs are considered brilliant fragments or sketches of what could be longer pop songs.",
    category: "facts",
  },
  {
    id: 138,
    question: "What collage art medium is Robert Pollard known for outside of music?",
    options: [
      "Oil painting",
      "Sculpture",
      "Collage art using cut-up images and text",
      "Photography",
    ],
    correctAnswer: 2,
    explanation: "Pollard creates collage art, which often appears as GBV album and single artwork.",
    category: "facts",
  },
  {
    id: 139,
    question: "GBV's output is often compared to what musical era's approach to releasing singles?",
    options: [
      "The 1950s jukebox era",
      "The 1960s British Invasion",
      "The 1980s synth-pop era",
      "The 2000s digital era",
    ],
    correctAnswer: 1,
    explanation: "GBV's prolific output and short, punchy songs are often compared to the 1960s British Invasion approach.",
    category: "facts",
  },
  {
    id: 140,
    question: "How are GBV's album titles often characterized?",
    options: [
      "Simple and literal",
      "Imaginative and evocative with surreal imagery",
      "Always self-titled",
      "Named after band members",
    ],
    correctAnswer: 1,
    explanation: "GBV album titles like 'Bee Thousand' and 'Under the Bushes Under the Stars' are imaginative and evocative.",
    category: "facts",
  },
  {
    id: 141,
    question: "What state is most associated with GBV's identity?",
    options: ["New York", "California", "Ohio", "Michigan"],
    correctAnswer: 2,
    explanation: "Ohio, specifically Dayton, is central to GBV's identity and history.",
    category: "facts",
  },
  {
    id: 142,
    question: "Which publication famously championed GBV and lo-fi rock in the 1990s?",
    options: ["Rolling Stone", "Spin", "Pitchfork", "NME"],
    correctAnswer: 2,
    explanation: "Pitchfork was an early champion of GBV and lo-fi indie rock in the 1990s.",
    category: "facts",
  },
  {
    id: 143,
    question: "What is a signature move Robert Pollard performs during concerts?",
    options: ["Stage diving", "High kicks like Pete Townshend", "Smashing guitars", "Playing behind his head"],
    correctAnswer: 1,
    explanation: "Pollard is known for his Pete Townshend-inspired high kicks during live performances.",
    category: "facts",
  },
  {
    id: 144,
    question: "About how many songs has Robert Pollard been estimated to have written?",
    options: ["500+", "1,000+", "2,000+", "5,000+"],
    correctAnswer: 2,
    explanation: "Robert Pollard has been estimated to have written well over 2,000 songs across all his projects.",
    category: "facts",
  },
  {
    id: 145,
    question: "Which Cars frontman produced a GBV album?",
    options: ["Benjamin Orr", "Ric Ocasek", "Greg Hawkes", "Elliot Easton"],
    correctAnswer: 1,
    explanation: "Ric Ocasek of The Cars produced Do the Collapse (1999).",
    category: "facts",
  },
  {
    id: 146,
    question: "What type of venues did early GBV shows typically take place in?",
    options: [
      "Arenas and stadiums",
      "Small bars, basements, and house parties",
      "Outdoor amphitheaters",
      "Churches",
    ],
    correctAnswer: 1,
    explanation: "Early GBV shows were typically in small bars, basements, and house parties in Dayton.",
    category: "facts",
  },
  {
    id: 147,
    question: "GBV is often grouped with which musical movement of the 1990s?",
    options: ["Grunge", "Lo-fi indie rock", "Britpop", "Emo"],
    correctAnswer: 1,
    explanation: "GBV is a flagship band of the 1990s lo-fi indie rock movement.",
    category: "facts",
  },
  {
    id: 148,
    question: "What makes GBV's post-reunion period (2010-present) particularly remarkable?",
    options: [
      "They stopped touring entirely",
      "They switched to electronic music",
      "Their extreme prolificacy, releasing multiple albums per year",
      "They signed to a major label",
    ],
    correctAnswer: 2,
    explanation: "Since reuniting, GBV has been extraordinarily prolific, often releasing 2-4 albums per year.",
    category: "facts",
  },
  {
    id: 149,
    question: "Which indie rock genre label is most commonly applied to GBV?",
    options: ["Dream pop", "Lo-fi indie rock", "Post-rock", "Shoegaze"],
    correctAnswer: 1,
    explanation: "Lo-fi indie rock is the genre label most commonly associated with GBV.",
    category: "facts",
  },
  {
    id: 150,
    question: "What notable physical act does Pollard do when toasting the crowd?",
    options: [
      "Throws his guitar pick",
      "Chugs a beer and kicks the cup",
      "Throws confetti",
      "Does a backflip",
    ],
    correctAnswer: 1,
    explanation: "Pollard is known for chugging beers and kicking the empty cup during GBV shows.",
    category: "facts",
  },
];

export function getDailyGbvTriviaQuestions(date?: Date): GbvTriviaQuestion[] {
  const now = date || new Date();
  const totalQuestions = gbvTriviaQuestions.length;
  const questionsPerDay = 5;

  const getEpochDay = (d: Date) => {
    const utc = Date.UTC(d.getFullYear(), d.getMonth(), d.getDate());
    return Math.floor(utc / 86400000);
  };

  const shuffleQuestions = (seed: number) => {
    const shuffled = [...gbvTriviaQuestions];
    let currentSeed = seed;
    for (let i = shuffled.length - 1; i > 0; i -= 1) {
      currentSeed = (currentSeed * 16807) % 2147483647;
      const j = currentSeed % (i + 1);
      [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
  };

  const cycleLength = Math.floor(totalQuestions / questionsPerDay);
  const dayIndex = getEpochDay(now) % cycleLength;
  const startIndex = dayIndex * questionsPerDay;
  const shuffledQuestions = shuffleQuestions(748291);

  return shuffledQuestions.slice(startIndex, startIndex + questionsPerDay);
}

export function getGbvTodayStorageKey(date?: Date): string {
  const now = date || new Date();
  return `gbv-trivia-${now.getFullYear()}-${now.getMonth() + 1}-${now.getDate()}`;
}

export function getGbvNextTriviaTime(): Date {
  const now = new Date();
  const tomorrow = new Date(now);
  tomorrow.setDate(tomorrow.getDate() + 1);
  tomorrow.setHours(0, 0, 0, 0);
  return tomorrow;
}
